"""expand library entities
Revision ID: 444e3998ae8d
Revises: e13d8371e6e6
Create Date: 2026-06-30 10:33:23.063778
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""expand library entities
Revision ID: 444e3998ae8d
Revises: e13d8371e6e6
Create Date: 2026-06-30 10:33:23.063778
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444e3998ae8d'
down_revision = 'e13d8371e6e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(bind)

    if not inspector.has_table('library_authors'):
        op.create_table('library_authors',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('biography', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_library_authors_name'), 'library_authors', ['name'], unique=False)

    if not inspector.has_table('library_publishers'):
        op.create_table('library_publishers',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('contact_info', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_library_publishers_name'), 'library_publishers', ['name'], unique=False)

    if not inspector.has_table('book_categories'):
        op.create_table('book_categories',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('default_rack', sa.String(length=50), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('name')
        )
    op.create_index(op.f('ix_book_categories_name'), 'book_categories', ['name'], unique=True)

    if not inspector.has_table('library_members'):
        op.create_table('library_members',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('member_type', sa.Enum('STUDENT', 'FACULTY', 'STAFF', 'EXTERNAL', name='membertype'), nullable=False),
            sa.Column('membership_date', sa.Date(), nullable=False),
            sa.Column('expiry_date', sa.Date(), nullable=True),
            sa.Column('max_books_allowed', sa.Integer(), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('user_id')
        )

    if not inspector.has_table('book_reservations'):
        op.create_table('book_reservations',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('book_id', sa.Integer(), nullable=False),
            sa.Column('member_id', sa.Integer(), nullable=False),
            sa.Column('reservation_date', sa.DateTime(), nullable=False),
            sa.Column('status', sa.Enum('PENDING', 'FULFILLED', 'CANCELLED', 'EXPIRED', name='reservationstatus'), nullable=False),
            sa.Column('notified_date', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(['book_id'], ['library_books.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['member_id'], ['library_members.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
    op.create_index(op.f('ix_book_reservations_book_id'), 'book_reservations', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_reservations_member_id'), 'book_reservations', ['member_id'], unique=False)

    if not inspector.has_table('library_fines'):
        op.create_table('library_fines',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('issue_id', sa.Integer(), nullable=True),
            sa.Column('member_id', sa.Integer(), nullable=False),
            sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
            sa.Column('reason', sa.String(length=255), nullable=False),
            sa.Column('is_paid', sa.Boolean(), nullable=False),
            sa.Column('payment_date', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(['issue_id'], ['book_issues.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['member_id'], ['library_members.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )

    with op.batch_alter_table('book_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('book_issues_ibfk_2', type_='foreignkey')
        batch_op.drop_index('ix_book_issues_student_id')
        batch_op.create_index(batch_op.f('ix_book_issues_member_id'), ['member_id'], unique=False)
        batch_op.create_foreign_key(None, 'library_members', ['member_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('library_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('publisher_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_library_books_author')
        batch_op.drop_index('ix_library_books_category')
        batch_op.create_foreign_key(None, 'library_authors', ['author_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'library_publishers', ['publisher_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'book_categories', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('publisher')
        batch_op.drop_column('category')
        batch_op.drop_column('author')

    with op.batch_alter_table('student_electives', schema=None) as batch_op:
        batch_op.alter_column('selected_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_electives', schema=None) as batch_op:
        batch_op.alter_column('selected_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)

    with op.batch_alter_table('library_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.add_column(sa.Column('publisher', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_library_books_category', ['category'], unique=False)
        batch_op.create_index('ix_library_books_author', ['author'], unique=False)
        batch_op.drop_column('category_id')
        batch_op.drop_column('publisher_id')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('book_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('book_issues_ibfk_2', 'students', ['student_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_book_issues_member_id'))
        batch_op.create_index('ix_book_issues_student_id', ['student_id'], unique=False)
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
