"""revamp_finance_models
Revision ID: 86ea4d69a162
Revises: 444e3998ae8d
Create Date: 2026-06-30 11:49:36.844981
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '86ea4d69a162'
down_revision = '444e3998ae8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_categories_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('expenses',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('fee_structures',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_structures_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structures_is_deleted'), ['is_deleted'], unique=False)

    op.create_table('staff_salaries',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CHEQUE', 'BANK_TRANSFER', 'UPI', 'ONLINE', name='paymentmethod'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_salaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_salaries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_salaries_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_salaries_user_id'), ['user_id'], unique=False)

    op.create_table('student_fees',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('fee_structure_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'PARTIAL', 'OVERDUE', 'WAIVED', name='feestatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_fees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_fees_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_fees_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_fees_student_id'), ['student_id'], unique=False)

    op.create_table('payments',
    sa.Column('student_fee_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'CHEQUE', 'BANK_TRANSFER', 'UPI', 'ONLINE', name='paymentmethod'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'PENDING', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_fee_id'], ['student_fees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_reference')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_student_fee_id'), ['student_fee_id'], unique=False)


    op.drop_table('fees')
    with op.batch_alter_table('student_electives', schema=None) as batch_op:
        batch_op.alter_column('selected_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_electives', schema=None) as batch_op:
        batch_op.alter_column('selected_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)

    op.create_table('fees',
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fee_type', mysql.ENUM('TUITION', 'EXAM', 'LIBRARY', 'LABORATORY', 'HOSTEL', 'TRANSPORT', 'OTHER'), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('paid_amount', mysql.FLOAT(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('paid_date', sa.DATE(), nullable=True),
    sa.Column('status', mysql.ENUM('PENDING', 'PAID', 'PARTIAL', 'OVERDUE', 'WAIVED'), nullable=False),
    sa.Column('semester', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receipt_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('payment_method', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('remarks', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='fees_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.create_index('receipt_number', ['receipt_number'], unique=True)
        batch_op.create_index('ix_fees_student_id', ['student_id'], unique=False)
        batch_op.create_index('ix_fees_is_deleted', ['is_deleted'], unique=False)
        batch_op.create_index('ix_fees_id', ['id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_student_fee_id'))
        batch_op.drop_index(batch_op.f('ix_payments_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('student_fees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_fees_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_fees_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_student_fees_id'))

    op.drop_table('student_fees')
    with op.batch_alter_table('staff_salaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_salaries_user_id'))
        batch_op.drop_index(batch_op.f('ix_staff_salaries_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_staff_salaries_id'))

    op.drop_table('staff_salaries')
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_structures_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_fee_structures_id'))

    op.drop_table('fee_structures')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_expenses_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_categories_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_expense_categories_id'))

    op.drop_table('expense_categories')
    # ### end Alembic commands ###
