"""Upgrade Library Models
Revision ID: e13d8371e6e6
Revises: cc9cb668516c
Create Date: 2026-06-30 10:20:31.278955
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'e13d8371e6e6'
down_revision = 'cc9cb668516c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_semesters', schema=None) as batch_op:
        batch_op.alter_column('minimum_credits',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_academic_semesters_curriculum_version_id'), ['curriculum_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_semesters_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_semesters_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('book_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renewals_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fine_paid', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('condition_on_issue', sa.Enum('NEW', 'GOOD', 'FAIR', 'POOR', 'DAMAGED', name='bookcondition'), nullable=True))
        batch_op.add_column(sa.Column('condition_on_return', sa.Enum('NEW', 'GOOD', 'FAIR', 'POOR', 'DAMAGED', name='bookcondition'), nullable=True))

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_branches_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branches_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_courses_department', type_='foreignkey')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('curricula', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_curricula_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curricula_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curricula_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curricula_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('curriculum_subjects', schema=None) as batch_op:
        batch_op.alter_column('branch_scope_key',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_mandatory',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('display_order',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_curriculum_subjects_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_subjects_elective_group_id'), ['elective_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_subjects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_subjects_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_subjects_semester_id'), ['semester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_subjects_subject_id'), ['subject_id'], unique=False)

    with op.batch_alter_table('curriculum_versions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_curriculum_versions_applicable_batch_start'), ['applicable_batch_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_versions_curriculum_id'), ['curriculum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_versions_effective_year'), ['effective_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_versions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_versions_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('elective_groups', schema=None) as batch_op:
        batch_op.alter_column('minimum_choices',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('maximum_choices',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_elective_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_elective_groups_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_elective_groups_semester_id'), ['semester_id'], unique=False)

    with op.batch_alter_table('faculty_assignments', schema=None) as batch_op:
        batch_op.alter_column('section_scope_key',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_faculty_assignments_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_assignments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_assignments_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_assignments_section_id'), ['section_id'], unique=False)

    with op.batch_alter_table('library_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('vendor', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('condition', sa.Enum('NEW', 'GOOD', 'FAIR', 'POOR', 'DAMAGED', name='bookcondition'), nullable=False))

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.alter_column('branch_scope_key',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_sections_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_sections_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sections_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sections_curriculum_version_id'), ['curriculum_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sections_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('student_electives', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('selected_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_student_electives_curriculum_subject_id'), ['curriculum_subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_electives_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_electives_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_electives_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('current_semester',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_students_admission_year'), ['admission_year'], unique=False)
        batch_op.drop_constraint('fk_students_section', type_='foreignkey')
        batch_op.drop_constraint('students_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('fk_students_course', type_='foreignkey')
        batch_op.drop_constraint('fk_students_branch', type_='foreignkey')
        batch_op.create_foreign_key(None, 'sections', ['section_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('subject_teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_teachers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subject_teachers_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('subject_types', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index('uq_subject_type_code')
        batch_op.drop_index('ix_subject_types_code')
        batch_op.create_index(batch_op.f('ix_subject_types_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_subject_types_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subject_types_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint('teachers_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('fk_teachers_branch', type_='foreignkey')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('timetable_versions', schema=None) as batch_op:
        batch_op.alter_column('branch_scope_key',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('section_scope_key',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('version_number',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_user_roles_id'))

    with op.batch_alter_table('timetable_versions', schema=None) as batch_op:
        batch_op.alter_column('version_number',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)
        batch_op.alter_column('section_scope_key',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('branch_scope_key',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_teachers_branch', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('teachers_ibfk_2', 'departments', ['department_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('subject_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_types_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_subject_types_id'))
        batch_op.drop_index(batch_op.f('ix_subject_types_code'))
        batch_op.create_index('ix_subject_types_code', ['code'], unique=False)
        batch_op.create_index('uq_subject_type_code', ['code'], unique=True)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)

    with op.batch_alter_table('subject_teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_teachers_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_subject_teachers_id'))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_students_branch', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_students_course', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('students_ibfk_2', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_students_section', 'sections', ['section_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_students_admission_year'))
        batch_op.alter_column('current_semester',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)

    with op.batch_alter_table('student_electives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_electives_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_electives_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_student_electives_id'))
        batch_op.drop_index(batch_op.f('ix_student_electives_curriculum_subject_id'))
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('selected_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               server_default=sa.text("'selected'"),
               existing_nullable=False)

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_sections_id'))
        batch_op.drop_index(batch_op.f('ix_sections_curriculum_version_id'))
        batch_op.drop_index(batch_op.f('ix_sections_course_id'))
        batch_op.drop_index(batch_op.f('ix_sections_branch_id'))
        batch_op.drop_index(batch_op.f('ix_sections_academic_year'))
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('branch_scope_key',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)

    with op.batch_alter_table('library_books', schema=None) as batch_op:
        batch_op.drop_column('condition')
        batch_op.drop_column('cover_image_url')
        batch_op.drop_column('pages')
        batch_op.drop_column('language')
        batch_op.drop_column('vendor')
        batch_op.drop_column('price')
        batch_op.drop_column('purchase_date')

    with op.batch_alter_table('faculty_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_assignments_section_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_assignments_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_faculty_assignments_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_assignments_academic_year'))
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               server_default=sa.text("'primary'"),
               existing_nullable=False)
        batch_op.alter_column('section_scope_key',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)

    with op.batch_alter_table('elective_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elective_groups_semester_id'))
        batch_op.drop_index(batch_op.f('ix_elective_groups_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_elective_groups_id'))
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('maximum_choices',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               existing_nullable=False)
        batch_op.alter_column('minimum_choices',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)

    with op.batch_alter_table('curriculum_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_versions_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_curriculum_versions_is_active'))
        batch_op.drop_index(batch_op.f('ix_curriculum_versions_id'))
        batch_op.drop_index(batch_op.f('ix_curriculum_versions_effective_year'))
        batch_op.drop_index(batch_op.f('ix_curriculum_versions_curriculum_id'))
        batch_op.drop_index(batch_op.f('ix_curriculum_versions_applicable_batch_start'))
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               server_default=sa.text("'draft'"),
               existing_nullable=False)

    with op.batch_alter_table('curriculum_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_subjects_subject_id'))
        batch_op.drop_index(batch_op.f('ix_curriculum_subjects_semester_id'))
        batch_op.drop_index(batch_op.f('ix_curriculum_subjects_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_curriculum_subjects_id'))
        batch_op.drop_index(batch_op.f('ix_curriculum_subjects_elective_group_id'))
        batch_op.drop_index(batch_op.f('ix_curriculum_subjects_branch_id'))
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('display_order',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('is_mandatory',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=False)
        batch_op.alter_column('branch_scope_key',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)

    with op.batch_alter_table('curricula', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curricula_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_curricula_id'))
        batch_op.drop_index(batch_op.f('ix_curricula_course_id'))
        batch_op.drop_index(batch_op.f('ix_curricula_branch_id'))
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_courses_department', 'departments', ['department_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_branches_id'))
        batch_op.drop_index(batch_op.f('ix_branches_course_id'))
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)

    with op.batch_alter_table('book_issues', schema=None) as batch_op:
        batch_op.drop_column('condition_on_return')
        batch_op.drop_column('condition_on_issue')
        batch_op.drop_column('fine_paid')
        batch_op.drop_column('renewals_count')

    with op.batch_alter_table('academic_semesters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_semesters_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_academic_semesters_id'))
        batch_op.drop_index(batch_op.f('ix_academic_semesters_curriculum_version_id'))
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
        batch_op.alter_column('minimum_credits',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)

    # ### end Alembic commands ###
